---
- name: configuring the apache server
  hosts: node2
  become: yes
  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]
    - name: installing the apache packages
      apt:
        name: apache2
        state: present
    - name: starting apache services
      service:
        name: apache2
        state: started
    - name: installing firewalld
      apt:
        name: firewalld
        state: present
    - name: add firewall rules
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
    - name: reload firewall rules
      systemd:
        name: firewalld
        state: reloaded
    - name: copying index file
      copy:
        src: index.html
        dest: /var/www/html/
    - name: copying style file
      copy:
        src: style.css
        dest: /var/www/html/
    - name: restarting the apache services
      service:
        name: apache2
        state: restarted
